import pytest

def test_that_fails():
    pytest.fail("This is a failure that should be happening.")
