def test_that_fails():
    """A function added temporarily to show that tests are being run."""
    raise ValueError("This error is supposed to happen.")
